export const SESSION_RESTORING = "SESSION_RESTORING";
export const SESSION_LOADING = "SESSION_LOADING";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SESSION_ERROR = "SESSION_ERROR";
export const SESSION_LOGOUT = "SESSION_LOGOUT";

// POST TYPES
export const POST_FETCH_ALL = "POST_FETCH_ALL";
export const POST_ADD = "POST_ADD";
export const POST_SELECT_IMAGE = "POST_SELECT_IMAGE";
export const POST_LIKE = "POST_LIKE";
export const POST_DISLIKE = "POST_DISLIKE";
export const POST_ADD_COMMENT = "POST_ADD_COMMENT";

// PROFILE TYPES
export const PROFILE_FETCH = "PROFILE_FETCH";
export const PROFILE_EDIT = "PROFILE_EDIT";
